### PR TITLE
[cmake] create a target for the MeshSD library

### PR DESCRIPTION
**Pull request by fabiencastan**
- [X] New MeshSDLibrary cmake target. This enables to use it externally as a library.
- [X] Update OpenMesh
- [X] Add OpenMesh Decimate Tool. It is very useful to reduce the density after the meshSD denoiser.
- [X] Add find_package OpenMP, to have the multi-threading enabled.
- [X] Eigen >= 3.3 now provides cmake config files making the `FindEigen3.cmake` useless (and even problematic as it overrides the config files).

### CODE REVIEW

**Comment by bldeng** [comment]
It seems that the pull request does not handle the case where there is no system-level Eigen installation available? On a Linux system with no Eigen installed, I got the following errors:

  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" (requested
  version 3.3) with any of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by fabiencastan** [comment]
Do you have a version of eigen >= 3.3 ?

In cmake, libraries can provide cmake config files. If they do not provide them, you have to create a FindXXX.cmake and try to retrieve the build options. So providing config files is the recommended way to do. But eigen has started to provide them only in version 3.3.
So unfortunately, we cannot support older versions if we switch to the new way of doing things in cmake.

**Comment by bldeng** [comment]
The problem arises when you compile it on a system that does not have Eigen installed, and need to download Eigen to a local folder. This is not uncommon (imagine a University PC lab where Eigen is not installed and students have no admin right). So we have to support local copies of Eigen provided by the user. That is why the original code allows the user to put Eigen into the external folder and check for that folder first. If Eigen is found there, then it will be added to the include path. Otherwise, CMakeLists.txt assumes there is a system-level installation of Eigen >= 3.3, and tries to call its FindEigen3.cmake command. The file FindEigen3.cmake provided in the original code is actually not used.

I think the original way of handling Eigen makes more sense. The user can either rely on system-level Eigen if it exists, or provide their own version of Eigen if they want to. I presume this would work with the new MeshSDLibrary target, if you simply remove Eigen from its target_link_libraries and add the Eigen path to its target_include_directories? We can use another variable to store the local Eigen path, if we want to avoid conflict with the system-level EIGEN3_INCLUDE_DIR variable.

**Comment by majioa** [comment]
@bldeng @fabiencastan ping?

**Pull request merged**
